export type AddonTerm={id:string;academic_session_id:string;name:string};
export type AddonArm={id:string;class_id:string;name:string};
export type AddonStudent={id:string;first_name:string;last_name:string;other_names?:string|null;preferred_name?:string|null;admission_number:string;current_class_id:string|null;current_arm_id:string|null;student_status?:string};
export type AddonFee={id:string;academic_session_id:string;term_id:string|null;class_id:string;arm_id:string|null;is_required:boolean};
export function termsForSession(terms:AddonTerm[],sessionId:string){return sessionId?terms.filter(t=>t.academic_session_id===sessionId):[];}
export function armsForClass(arms:AddonArm[],classId:string){return classId?arms.filter(a=>a.class_id===classId):[];}
export function studentsForSelection(students:AddonStudent[],classId:string,armId=""){return classId?students.filter(s=>s.student_status!=="inactive"&&s.current_class_id===classId&&(!armId||s.current_arm_id===armId)):[];}
export function searchStudents(students:AddonStudent[],query:string){const q=query.trim().toLowerCase();if(!q)return students;return students.filter(s=>[s.first_name,s.last_name,s.other_names,s.preferred_name,s.admission_number].filter(Boolean).some(v=>String(v).toLowerCase().includes(q)));}
export function feesForSelection<T extends AddonFee>(fees:T[],selection:{sessionId:string;termId:string;classId:string;armId:string}){return fees.filter(f=>!f.is_required&&f.academic_session_id===selection.sessionId&&f.class_id===selection.classId&&(selection.termId?(f.term_id===selection.termId||f.term_id===null):f.term_id===null)&&(!f.arm_id||f.arm_id===selection.armId));}
export function validateAddonSelection(input:{session?:string;term?:string;class?:string;arm?:string;student?:string},data:{sessions:{id:string}[];terms:AddonTerm[];classes:{id:string}[];arms:AddonArm[];students:AddonStudent[]}){const sessionId=data.sessions.some(x=>x.id===input.session)?input.session??"":data.sessions[0]?.id??"";const classId=data.classes.some(x=>x.id===input.class)?input.class??"":"";const termId=data.terms.some(x=>x.id===input.term&&x.academic_session_id===sessionId)?input.term??"":"";const armId=classId&&data.arms.some(x=>x.id===input.arm&&x.class_id===classId)?input.arm??"":"";const studentId=classId&&data.students.some(x=>x.id===input.student&&x.current_class_id===classId&&(!armId||x.current_arm_id===armId))?input.student??"":"";return {sessionId,termId,classId,armId,studentId};}

