import { describe, expect, it } from "vitest";
import { armsForClass, feesForSelection, searchStudents, studentsForSelection, termsForSession, validateAddonSelection, type AddonStudent } from "./student-addon-filters";
const terms=[{id:"t1",name:"First",academic_session_id:"s1"},{id:"t2",name:"Second",academic_session_id:"s2"}];
const arms=[{id:"a1",name:"Gold",class_id:"c1"},{id:"a2",name:"Blue",class_id:"c2"}];
const students:AddonStudent[]=[{id:"u1",first_name:"Ada",last_name:"Okafor",other_names:"Chi",admission_number:"SN-001",current_class_id:"c1",current_arm_id:"a1"},{id:"u2",first_name:"Bola",last_name:"Ali",preferred_name:"Bee",admission_number:"SN-002",current_class_id:"c1",current_arm_id:null},{id:"u3",first_name:"Cara",last_name:"Doe",admission_number:"SN-003",current_class_id:"c2",current_arm_id:"a2"},{id:"u4",first_name:"Dan",last_name:"Eze",admission_number:"SN-004",current_class_id:"c1",current_arm_id:"a1",student_status:"inactive"}];
const data={sessions:[{id:"s1"},{id:"s2"}],terms,classes:[{id:"c1"},{id:"c2"}],arms,students};
describe("student add-on cascading filters",()=>{
 it("filters dependent terms, arms, active students, and arm students",()=>{expect(termsForSession(terms,"s1").map(x=>x.id)).toEqual(["t1"]);expect(armsForClass(arms,"c1").map(x=>x.id)).toEqual(["a1"]);expect(studentsForSelection(students,"c1").map(x=>x.id)).toEqual(["u1","u2"]);expect(studentsForSelection(students,"c1","a1").map(x=>x.id)).toEqual(["u1"])});
 it("clears incompatible and cross-school ids and never defaults a student",()=>{expect(validateAddonSelection({session:"s1"},data).studentId).toBe("");expect(validateAddonSelection({session:"s1",term:"t2",class:"c1",arm:"a2",student:"u3"},data)).toEqual({sessionId:"s1",termId:"",classId:"c1",armId:"",studentId:""});expect(validateAddonSelection({session:"foreign",class:"foreign",student:"foreign"},data)).toEqual({sessionId:"s1",termId:"",classId:"",armId:"",studentId:""})});
 it("rejects student/class and student/arm mismatches",()=>{expect(validateAddonSelection({session:"s1",class:"c1",student:"u3"},data).studentId).toBe("");expect(validateAddonSelection({session:"s1",class:"c1",arm:"a1",student:"u2"},data).studentId).toBe("")});
 it("filters optional fees by session, term fallback, class, and arm",()=>{const fees=[{id:"ok-term",academic_session_id:"s1",term_id:"t1",class_id:"c1",arm_id:"a1",is_required:false},{id:"ok-session",academic_session_id:"s1",term_id:null,class_id:"c1",arm_id:null,is_required:false},{id:"required",academic_session_id:"s1",term_id:"t1",class_id:"c1",arm_id:"a1",is_required:true},{id:"wrong-arm",academic_session_id:"s1",term_id:"t1",class_id:"c1",arm_id:"a2",is_required:false}];expect(feesForSelection(fees,{sessionId:"s1",termId:"t1",classId:"c1",armId:"a1"}).map(x=>x.id)).toEqual(["ok-term","ok-session"]);expect(feesForSelection(fees,{sessionId:"s2",termId:"",classId:"c1",armId:""})).toEqual([])});
});
describe("student search",()=>{const candidates=studentsForSelection(students,"c1");it.each([["ada","u1"],["OKAFOR","u1"],["chi","u1"],["bee","u2"],["sn-002","u2"]])("matches %s",(query,id)=>expect(searchStudents(candidates,query).map(x=>x.id)).toContain(id));it("never expands beyond filtered candidates",()=>expect(searchStudents(candidates,"cara")).toEqual([]))});
