/* eslint-disable @typescript-eslint/no-explicit-any */
import {describe,expect,it} from "vitest";
import {validateRows} from "./process";
import type {TenantSchoolContext} from "@/lib/tenant/get-school-context";
const base={classes:[{id:'c1',code:'JSS_1'}],class_arms:[{id:'a1',class_id:'c1',code:'A'}],school_sections:[{id:'sec',code:'SECONDARY'}],students:[],staff_profiles:[],parent_guardians:[],subjects:[],fee_categories:[{id:'cat',code:'TUITION'}],fee_items:[{id:'fi',code:'TRANSPORT',is_mandatory:false}],academic_sessions:[{id:'s1',name:'2026/2027'}],terms:[{id:'t1',name:'first',academic_session_id:'s1'}],class_fee_structures:[{id:'cf',academic_session_id:'s1',term_id:'t1',class_id:'c1',arm_id:null,fee_item_id:'fi',amount:5000,is_required:false}],student_optional_fees:[]};
function context(overrides:Record<string,unknown[]>={}){const tables={...base,...overrides} as Record<string,unknown[]>;const supabase={from:(table:string)=>{const q:any={select:()=>q,eq:()=>q,then:(resolve:(v:unknown)=>void)=>resolve({data:tables[table]??[]})};return q;}};return {supabase,schoolId:'school',profileId:'profile',userId:'user',roles:['school_admin']} as unknown as TenantSchoolContext;}
describe("import validation",()=>{
 it("accepts a valid student and rejects unknown class/arm and future DOB",async()=>{const valid=await validateRows('students',[{admission_number:'S1',first_name:'Ada',last_name:'Okafor',class_code:'JSS_1',arm_code:'A'}],context());expect(valid.valid).toBe(1);const bad=await validateRows('students',[{admission_number:'S2',first_name:'Ada',last_name:'O',class_code:'BAD',arm_code:'Z',date_of_birth:'2999-01-01'}],context());expect(bad.invalid).toBe(1);expect(bad.rows[0].issues.map(i=>i.code)).toEqual(expect.arrayContaining(['unknown_class','future_date']));});
 it("warns on existing admission/staff numbers and rejects invalid staff category",async()=>{const student=await validateRows('students',[{admission_number:'S1',first_name:'Ada',last_name:'Okafor',class_code:'JSS_1'}],context({students:[{id:'x',admission_number:'S1'}]}));expect(student.warnings).toBe(1);const staff=await validateRows('staff',[{staff_number:'T1',first_name:'Ayo',last_name:'Ade',staff_category:'invalid',employment_date:'2999-01-01'}],context());expect(staff.rows[0].issues.map(i=>i.code)).toEqual(expect.arrayContaining(['invalid_category','future_date']));});
 it("enforces fee type and resolves optional add-on configuration",async()=>{const mismatch=await validateRows('class-fees',[{academic_session_name:'2026/2027',class_code:'JSS_1',fee_item_code:'TRANSPORT',amount:'5000',fee_type:'compulsory'}],context());expect(mismatch.rows[0].issues.some(i=>i.code==='fee_type_mismatch')).toBe(true);const addon=await validateRows('student-addons',[{student_admission_number:'S1',academic_session_name:'2026/2027',term_name:'first',optional_fee_item_code:'TRANSPORT',amount:''}],context({students:[{id:'st',admission_number:'S1',current_class_id:'c1',current_arm_id:'a1'}]}));expect(addon.valid).toBe(1);});
 it("rejects cross-tenant-style unresolved references",async()=>{const link=await validateRows('guardian-links',[{student_admission_number:'OUTSIDE',guardian_phone:'0801',relationship_to_student:'Mother'}],context());expect(link.invalid).toBe(1);});
});

