import type { ImportModule } from "./types";
export type ImportDefinition={title:string;purpose:string;columns:readonly string[];required:readonly string[];recordsPath:string};
export const definitions:Record<ImportModule,ImportDefinition>={
 students:{title:"Students",purpose:"Create students and optionally connect guardians.",columns:["admission_number","first_name","last_name","other_names","preferred_name","gender","date_of_birth","class_code","arm_code","admission_date","student_status","nationality","state_of_origin","lga","home_address","blood_group","genotype","allergies","medical_notes","guardian_first_name","guardian_last_name","guardian_phone","guardian_email","guardian_relationship"],required:["admission_number","first_name","last_name","class_code"],recordsPath:"/dashboard/school-admin/students"},
 staff:{title:"Staff",purpose:"Create academic, management, support, and non-academic staff.",columns:["staff_number","first_name","last_name","other_names","gender","phone","email","address","date_of_birth","employment_date","employment_status","staff_category","job_title","department","qualification","emergency_contact_name","emergency_contact_phone"],required:["staff_number","first_name","last_name","staff_category"],recordsPath:"/dashboard/school-admin/staff"},
 guardians:{title:"Parents/Guardians",purpose:"Create guardian contact records without duplicates.",columns:["first_name","last_name","other_names","relationship_label","phone","alternate_phone","email","occupation","address","city","state"],required:["first_name","last_name","phone"],recordsPath:"/dashboard/school-admin/parents"},
 "guardian-links":{title:"Student-Guardian Links",purpose:"Connect existing students and guardians.",columns:["student_admission_number","guardian_phone","guardian_email","relationship_to_student","is_primary","can_pick_up","receives_sms","receives_email"],required:["student_admission_number","relationship_to_student"],recordsPath:"/dashboard/school-admin/students"},
 subjects:{title:"Subjects",purpose:"Create school subjects and resolve optional sections.",columns:["name","code","section_code","subject_type","is_active"],required:["name","code","subject_type"],recordsPath:"/dashboard/school-admin/setup/subjects"},
 "fee-items":{title:"Fee Items",purpose:"Create compulsory or optional fee definitions without amounts.",columns:["category_code","name","code","description","billing_frequency","fee_type","applies_to","is_active"],required:["name","code","billing_frequency","fee_type"],recordsPath:"/dashboard/school-admin/finance/fees"},
 "class-fees":{title:"Class Fees",purpose:"Set class fee prices for a session or term.",columns:["academic_session_name","term_name","class_code","arm_code","fee_item_code","amount","fee_type"],required:["academic_session_name","class_code","fee_item_code","amount","fee_type"],recordsPath:"/dashboard/school-admin/finance/fees"},
 "student-addons":{title:"Student Add-ons",purpose:"Assign configured optional fees to students.",columns:["student_admission_number","academic_session_name","term_name","optional_fee_item_code","amount","notes"],required:["student_admission_number","academic_session_name","optional_fee_item_code"],recordsPath:"/dashboard/school-admin/finance/student-addons"}
};
export function templateCsv(module:ImportModule){return definitions[module].columns.join(",")+"\r\n";}
