"use client";
import { useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import type { ImportDefinition } from "@/lib/imports/templates";
import type { ImportModule, ImportResult, ValidatedRow } from "@/lib/imports/types";

export function CsvTemplateButton({module}:{module:ImportModule}){return <a className="inline-flex min-h-11 items-center justify-center rounded-xl border bg-white px-4 text-sm font-semibold" href={`/api/imports/${module}?template=1`}>Download CSV template</a>}
export function ImportInstructions({}: {definition:ImportDefinition}){return <div className="rounded-xl bg-muted p-4 text-sm leading-6"><p className="font-semibold">Before uploading</p><ol className="mt-2 list-decimal pl-5"><li>Download and keep the exact column headings.</li><li>Save the completed file as UTF-8 CSV.</li><li>Preview and fix blocked rows before confirming.</li><li>Existing matching records are skipped; imports never overwrite automatically.</li></ol></div>}
export function ImportValidationSummary({result}:{result:ImportResult}){return <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Total",result.total],["Ready",result.valid],["Warnings",result.warnings],["Blocked",result.invalid]].map(([l,v])=><div className="rounded-xl border p-3" key={l}><p className="text-xs text-muted-foreground">{l}</p><p className="text-xl font-bold">{v}</p></div>)}</div>}
function status(row:ValidatedRow){return row.issues.some(i=>i.severity==='error')?'Blocked':row.issues.length?'Warning':'Ready'}
export function ImportPreviewTable({result,columns}:{result:ImportResult;columns:readonly string[]}){return <><div className="space-y-3 md:hidden">{result.rows.map(r=><div className="rounded-xl border p-4" key={r.rowNumber}><div className="flex justify-between"><b>Row {r.rowNumber}</b><span>{status(r)}</span></div><dl className="mt-2 grid grid-cols-2 gap-2 text-xs">{columns.slice(0,6).map(c=><div key={c}><dt className="text-muted-foreground">{c.replaceAll('_',' ')}</dt><dd className="break-words">{r.normalized[c]||'—'}</dd></div>)}</dl>{r.issues.length?<ul className="mt-2 text-xs text-red-700">{r.issues.map((i,x)=><li key={x}>{i.message}</li>)}</ul>:null}</div>)}</div><div className="hidden overflow-x-auto rounded-xl border md:block"><table className="min-w-[900px] text-left text-xs"><thead className="bg-muted"><tr><th className="p-3">Row</th><th>Status</th>{columns.slice(0,8).map(c=><th key={c}>{c.replaceAll('_',' ')}</th>)}<th>Issues</th></tr></thead><tbody>{result.rows.map(r=><tr className="border-t align-top" key={r.rowNumber}><td className="p-3">{r.rowNumber}</td><td>{status(r)}</td>{columns.slice(0,8).map(c=><td className="max-w-40 break-words pr-3" key={c}>{r.normalized[c]||'—'}</td>)}<td className="max-w-64 text-red-700">{r.issues.map(i=>i.message).join(' ')}</td></tr>)}</tbody></table></div></>}
export function ImportCompletionSummary({result,module,recordsPath,onAgain}:{result:ImportResult;module:ImportModule;recordsPath:string;onAgain:()=>void}){return <div className="space-y-4 rounded-xl border p-5"><h2 className="text-xl font-bold">Import complete</h2><div className="grid grid-cols-3 gap-3"><div><small>Created</small><b className="block text-xl">{result.created}</b></div><div><small>Skipped</small><b className="block text-xl">{result.skipped}</b></div><div><small>Failed</small><b className="block text-xl">{result.failed}</b></div></div><div className="flex flex-col gap-2 sm:flex-row"><Link className="inline-flex min-h-11 items-center justify-center rounded-xl bg-primary px-4 text-sm font-semibold text-white" href={recordsPath}>View records</Link>{result.jobId&&result.failed?<a className="inline-flex min-h-11 items-center justify-center rounded-xl border px-4 text-sm font-semibold" href={`/api/imports/${module}?job=${result.jobId}`}>Download error CSV</a>:null}<Button variant="outline" onClick={onAgain}>Start another import</Button></div></div>}
export function ImportWorkflow({module,definition}:{module:ImportModule;definition:ImportDefinition}){const [file,setFile]=useState<File|null>(null),[result,setResult]=useState<ImportResult|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[complete,setComplete]=useState(false);async function submit(mode:'preview'|'import'){if(!file)return;setBusy(true);setError('');const body=new FormData();body.set('file',file);body.set('mode',mode);try{const response=await fetch(`/api/imports/${module}`,{method:'POST',body});const data=await response.json();if(!response.ok)throw new Error(data.error||'Import failed.');setResult(data);if(mode==='import'){setComplete(true);window.dispatchEvent(new CustomEvent('schoolnest:toast',{detail:{type:data.failed?'error':'success',message:`Import complete: ${data.created} created, ${data.skipped} skipped, ${data.failed} failed.`}}));}}catch(e){setError(e instanceof Error?e.message:'Import failed.');}finally{setBusy(false)}}if(complete&&result)return <ImportCompletionSummary result={result} module={module} recordsPath={definition.recordsPath} onAgain={()=>{setComplete(false);setResult(null);setFile(null)}}/>;return <div className="space-y-5"><ImportInstructions definition={definition}/><label className="flex min-h-36 cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed p-5 text-center"><b>{file?file.name:'Choose a CSV file'}</b><span className="mt-1 text-sm text-muted-foreground">CSV only · maximum 2 MB · maximum 2,000 rows</span><input className="sr-only" type="file" accept=".csv,text/csv" onChange={e=>{setFile(e.target.files?.[0]??null);setResult(null);setComplete(false)}}/></label>{error?<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>:null}{!result?<Button className="w-full sm:w-auto" disabled={!file||busy} onClick={()=>submit('preview')}>{busy?'Validating…':'Validate and preview'}</Button>:<><ImportValidationSummary result={result}/><ImportPreviewTable result={result} columns={definition.columns}/><div className="flex flex-col gap-2 sm:flex-row"><Button disabled={result.valid===0||busy} onClick={()=>submit('import')}>{busy?'Importing…':`Import ${result.valid} valid rows`}</Button><Button variant="outline" onClick={()=>setResult(null)}>Choose another file</Button></div></>}</div>}


