export type AttendanceStatus='present'|'absent'|'late'|'excused';export type Assignment={schoolId:string;sessionId:string;classId:string;armId:string|null;staffProfileId:string;active:boolean;startsOn?:string|null;endsOn?:string|null};
export function assignmentAuthorizes(a:Assignment,input:{schoolId:string;sessionId:string;classId:string;armId:string|null;staffProfileId:string;date:string}){return a.active&&a.schoolId===input.schoolId&&a.sessionId===input.sessionId&&a.classId===input.classId&&a.staffProfileId===input.staffProfileId&&(!a.armId||!input.armId||a.armId===input.armId)&&(!a.startsOn||a.startsOn<=input.date)&&(!a.endsOn||a.endsOn>=input.date)}
export function validateAttendanceDate(date:string,today:string){return /^\d{4}-\d{2}-\d{2}$/.test(date)&&date<=today}
export function attendanceCounts(entries:{status:AttendanceStatus|null}[]){return entries.reduce((a,e)=>{a[e.status??'unmarked']++;return a},{present:0,absent:0,late:0,excused:0,unmarked:0} as Record<AttendanceStatus|'unmarked',number>)}
export function validateEntries(entries:{status:AttendanceStatus|null;remarks?:string|null}[]){const unmarked=entries.filter(e=>!e.status).length;if(unmarked)return `${unmarked} students still need an attendance status before submission.`;if(entries.some(e=>e.status==='excused'&&!e.remarks?.trim()))return 'Excused attendance requires a reason.';return null}
export function syncRoster(snapshot:string[],eligible:string[],registerStatus:string){if(registerStatus!=='draft')return {students:snapshot,added:0,error:'Roster sync is available only for draft registers.'};const add=eligible.filter(id=>!snapshot.includes(id));return {students:[...snapshot,...add],added:add.length,error:null}}
export type Announcement={id:string;status:'draft'|'scheduled'|'published'|'archived';publishAt:string|null;expiresAt:string|null;pinned:boolean;read:boolean};
export function announcementEffective(a:Announcement,now:string){return ['published','scheduled'].includes(a.status)&&Boolean(a.publishAt&&a.publishAt<=now)&&(!a.expiresAt||a.expiresAt>now)}
export function sortAnnouncementFeed(rows:Announcement[]){return [...rows].sort((a,b)=>Number(a.read)-Number(b.read)||Number(b.pinned)-Number(a.pinned)||String(b.publishAt).localeCompare(String(a.publishAt)))}
export function canTargetAnnouncement(actor:'admin'|'teacher'|'parent',scope:'school'|'roles'|'classes',assigned:boolean){return actor==='admin'||(actor==='teacher'&&scope==='classes'&&assigned)}
