export type Arm={id:string;class_id:string;name:string};export const armsForClass=(arms:Arm[],classId:string)=>classId?arms.filter(a=>a.class_id===classId):[];
export type Staff={id:string;first_name:string;last_name:string;staff_number:string;job_title?:string|null;department?:string|null;employment_status:string;user_profile_id?:string|null};export const activeStaff=(rows:Staff[])=>rows.filter(s=>s.employment_status==='active');export const searchStaff=(rows:Staff[],q:string)=>{const n=q.trim().toLowerCase();return activeStaff(rows).filter(s=>!n||[s.first_name,s.last_name,s.staff_number,s.job_title,s.department].filter(Boolean).some(v=>String(v).toLowerCase().includes(n)))};export const portalLabel=(s:Staff)=>s.user_profile_id?'Portal linked':'No portal account is linked to this staff member.';
export function rosterSyncSummary(eligible:string[],snapshot:string[]){const unique=[...new Set(eligible)],existing=new Set(snapshot),added=unique.filter(id=>!existing.has(id));return{eligibleCount:unique.length,existingSnapshotCount:snapshot.length,newlyAddedCount:added.length,alreadyPresentCount:unique.length-added.length,historicalPreservedCount:snapshot.filter(id=>!unique.includes(id)).length,studentIds:[...snapshot,...added]}}
export const hasUnsavedChanges=(saved:unknown,current:unknown)=>JSON.stringify(saved)!==JSON.stringify(current);
export function attendancePercentage(rows:{status:string|null}[]){if(!rows.length)return 0;const presentEquivalent=rows.filter(x=>x.status==='present'||x.status==='late').length;return Math.round(presentEquivalent*1000/rows.length)/10}
export function recordedDayTrend(rows:{date:string;status:string|null;classId?:string}[],days:number){const dates=[...new Set(rows.map(x=>x.date))].sort().reverse().slice(0,days),selected=rows.filter(x=>dates.includes(x.date));return{recordedDays:dates.length,rate:attendancePercentage(selected),absent:selected.filter(x=>x.status==='absent').length,late:selected.filter(x=>x.status==='late').length}}
export function normalizeParentFilters(input:{child?:string;session?:string;term?:string;range?:string;from?:string;to?:string},data:{children:string[];sessions:string[];terms:{id:string;sessionId:string;startsOn?:string;endsOn?:string}[]},today:string){const childId=data.children.includes(input.child??'')?input.child!:data.children.length===1?data.children[0]:'';const sessionId=data.sessions.includes(input.session??'')?input.session!:data.sessions[0]??'';const term=data.terms.find(t=>t.id===input.term&&t.sessionId===sessionId),termId=term?.id??'';const range=['term','30','custom'].includes(input.range??'')?input.range!:'term';let from=range==='custom'?(input.from??''):range==='30'?new Date(new Date(today+'T00:00:00Z').getTime()-29*86400000).toISOString().slice(0,10):term?.startsOn??'';let to=range==='custom'?(input.to??today):range==='term'?term?.endsOn??today:today;if(from&&to&&from>to){from='';to=''}return{childId,sessionId,termId,range,from,to}}
export type Target={type:'role'|'class'|'arm';role?:string;classId?:string;armId?:string};export const targetKey=(t:Target)=>`${t.type}:${t.role??''}:${t.classId??''}:${t.armId??''}`;export const dedupeTargets=(rows:Target[])=>[...new Map(rows.map(t=>[targetKey(t),t])).values()];export function validateTargets(scope:'school'|'roles'|'classes',targets:Target[],allowedRoles:string[]){const rows=dedupeTargets(targets);if(scope==='school')return rows.length?'School-wide announcements cannot include narrower targets.':null;if(scope==='roles')return rows.length&&rows.every(t=>t.type==='role'&&t.role&&allowedRoles.includes(t.role))?null:'Choose one or more supported role targets.';return rows.length&&rows.every(t=>(t.type==='class'||t.type==='arm')&&t.classId&&(t.type!=='arm'||t.armId))?null:'Choose one or more valid class or arm targets.'}
export function teacherTargetsAllowed(targets:Target[],assignments:{classId:string;armId:string|null}[]){return targets.every(t=>t.classId&&assignments.some(a=>a.classId===t.classId&&(!t.armId||!a.armId||a.armId===t.armId)))}
export const uniqueAudienceCount=(ids:string[][])=>new Set(ids.flat()).size;
export function filterAnnouncements<T extends {title:string;status:string;audience_scope:string;created_at:string;publish_at?:string|null;expires_at?:string|null}>(rows:T[],f:{status?:string;audience?:string;q?:string;date?:string},now:string,page=1,size=25){const filtered=rows.filter(x=>(!f.status||x.status===f.status)&&(!f.audience||x.audience_scope===f.audience)&&(!f.q||x.title.toLowerCase().includes(f.q.toLowerCase()))&&(!f.date||x.created_at.slice(0,10)===f.date)).filter(x=>f.status||x.status==='draft'||x.status==='published'||(x.status==='scheduled'&&Boolean(x.publish_at&&x.publish_at>now))||x.status==='archived');return{rows:filtered.slice((page-1)*size,page*size),total:filtered.length,pages:Math.max(1,Math.ceil(filtered.length/size))}}
