"use client";
import { useMemo, useState } from "react";
import { ActionForm } from "@/components/forms/action-form";
import { Field, SelectField, TextAreaField } from "@/components/dashboard/field";
import type { ActionState } from "@/app/dashboard/school-admin/setup/actions";
import { formatMoney } from "@/lib/finance/helpers";
import { maxDateTimeForCompletedAction } from "@/lib/dates";

type Student = { id: string; name: string }; type Invoice = { id: string; student_id: string; invoice_number: string; balance_amount: number; total_amount: number; context: string };
export function ManualPaymentForm({ action, students, invoices }: { action: (state: ActionState, data: FormData) => Promise<ActionState>; students: Student[]; invoices: Invoice[] }) {
 const [studentId,setStudentId]=useState(""); const [invoiceId,setInvoiceId]=useState(""); const [unallocated,setUnallocated]=useState(false); const eligible=useMemo(()=>invoices.filter(i=>i.student_id===studentId),[invoices,studentId]);
 const chooseStudent=(id:string)=>{setStudentId(id); const found=invoices.filter(i=>i.student_id===id); setInvoiceId(found.length===1?found[0].id:"");};
 return <ActionForm action={action} submitLabel="Record payment"><div className="grid gap-4 md:grid-cols-3"><label className="block"><span className="mb-2 block text-sm font-semibold">Student <span className="text-red-600">*</span></span><select className="h-12 w-full rounded-xl border px-4" name="student_id" required value={studentId} onChange={e=>chooseStudent(e.target.value)}><option value="">Choose student</option>{students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="block"><span className="mb-2 block text-sm font-semibold">Invoice{!unallocated?<span className="text-red-600"> *</span>:null}</span><select className="h-12 w-full rounded-xl border px-4 disabled:bg-muted" name="invoice_id" required={!unallocated} disabled={!studentId||unallocated} value={invoiceId} onChange={e=>setInvoiceId(e.target.value)}><option value="">{studentId?"Choose invoice":"Select a student first"}</option>{eligible.map(i=><option key={i.id} value={i.id}>{i.invoice_number} · {i.context} · total {formatMoney(i.total_amount)} · due {formatMoney(i.balance_amount)}</option>)}</select>{studentId&&eligible.length===0&&!unallocated?<span className="mt-1 block text-xs text-amber-700">This student has no outstanding invoices.</span>:null}</label><Field label="Amount" name="amount" type="number" min="0.01" step="0.01" required /><SelectField label="Method" name="payment_method" defaultValue="cash" required><option value="cash">Cash</option><option value="bank_transfer">Bank transfer</option><option value="pos">POS</option><option value="cheque">Cheque</option><option value="mobile_money">Mobile money</option><option value="other">Other</option></SelectField><SelectField label="Status" name="payment_status" defaultValue="confirmed" required><option value="confirmed">Confirmed</option><option value="pending">Pending</option></SelectField><Field label="Paid at" name="paid_at" type="datetime-local" max={maxDateTimeForCompletedAction()} defaultValue={maxDateTimeForCompletedAction()} required /><Field label="Payer name" name="payer_name" /><Field label="Payer phone" name="payer_phone" type="tel" /><Field label="Bank name" name="bank_name" /></div><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={unallocated} onChange={e=>{setUnallocated(e.target.checked);setInvoiceId("");}} /> Record an unallocated payment</label>{unallocated?<TextAreaField label="Reason for unallocated payment" name="transaction_note" required />:<TextAreaField label="Transaction note" name="transaction_note" />}</ActionForm>;
}

